Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,7 +31,7 @@ jobs:
       - name: Install Dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install -yq gettext libncurses5-dev rsync xsltproc wget
+          sudo apt-get install -yq gettext libncurses5-dev rsync xsltproc wget file
 
       - name: Create Directories
         run: |
@@ -40,6 +40,7 @@ jobs:
 
       - name: Prepare Build Environment
         run: |
+          source $GITHUB_ENV
           cd "$SDK_DL_DIR"
           if ! ( wget -q -O - "$SDK_URL_PATH/sha256sums" | grep -- "$SDK_NAME" > sha256sums.small 2>/dev/null ) ; then
             echo "Cannot find ${SDK_NAME} file in sha256sums."
@@ -47,14 +48,17 @@ jobs:
           fi
           SDK_FILE="$(awk '{print $2}' sha256sums.small | sed 's/*//g')"
           wget -q -O "$SDK_DL_DIR/$SDK_FILE" "$SDK_URL_PATH/$SDK_FILE"
+          echo "Downloaded file type:"
+          file "$SDK_DL_DIR/$SDK_FILE"
           if ! sha256sum -c sha256sums.small >/dev/null 2>&1 ; then
             echo "SDK cannot be verified!"
             exit 1
           fi
-          tar -Jxf "$SDK_DL_DIR/$SDK_FILE" -C "$SDK_HOME" --strip=1
+          tar -Jxf "$SDK_DL_DIR/$SDK_FILE" -C "$SDK_HOME" --strip=1 || { echo "Failed to extract SDK"; exit 1; }
 
       - name: Build Packages
         run: |
+          source $GITHUB_ENV
           cd "$SDK_HOME"
           ./scripts/feeds update -a > /dev/null 2>&1
           ./scripts/feeds install -a > /dev/null 2>&1
